import type { QuestStep } from './store';

export const newVoterRoadmap: QuestStep[] = [
  { id: 'eligibility', title: 'Eligibility Check', description: 'Verify your age and citizenship requirements against ECI norms', icon: 'search-check', completed: false, active: true, whatYouNeed: ['Date of birth', 'Citizenship status', 'Current address'], commonMistake: 'Many assume they auto-qualify at 18 — you must be 18 ON a qualifying date (Jan 1, Apr 1, Jul 1, or Oct 1). Citizens aged 17+ can submit an advance Form 6 application.' },
  { id: 'registration', title: 'Voter Registration (Form 6)', description: 'Submit Form 6 online or at your local BLO office', icon: 'clipboard-list', completed: false, active: false, whatYouNeed: ['Aadhaar card or ID proof', 'Address proof (utility bill)', 'Passport-size photo'], commonMistake: 'Uploading blurry photos or mismatched names leads to rejection. Double-check all details.', links: [{ text: 'ECI Voters Portal (Apply Online)', url: 'https://voters.eci.gov.in/' }] },
  { id: 'tracking', title: 'Application Tracking', description: 'Track your voter registration application status online', icon: 'search', completed: false, active: false, whatYouNeed: ['Application reference number', 'Mobile number used in application'], commonMistake: 'Not checking status and missing the BLO verification visit.', links: [{ text: 'Track Application Status', url: 'https://voters.eci.gov.in/' }] },
  { id: 'epic', title: 'Voter ID / e-EPIC Download', description: 'Get your EPIC card or download e-EPIC from voterportal.eci.gov.in', icon: 'credit-card', completed: false, active: false, whatYouNeed: ['EPIC number from enrollment', 'Registered mobile number'], commonMistake: 'Forgetting to link your mobile number during registration — required for e-EPIC.', links: [{ text: 'Download e-EPIC', url: 'https://voters.eci.gov.in/' }] },
  { id: 'candidate-kyc', title: 'Candidate Research', description: 'Review candidate profiles, assets, and criminal records', icon: 'users', completed: false, active: false, whatYouNeed: ['Access to ADR/MyNeta portal', 'Your constituency name'], commonMistake: 'Relying only on party advertisements instead of checking official affidavit data.', links: [{ text: 'Official ECI Candidate Affidavits', url: 'https://affidavit.eci.gov.in/' }] },
  { id: 'polling-station', title: 'Know Your Polling Booth', description: 'Find your designated polling station using EPIC number', icon: 'map-pin', completed: false, active: false, whatYouNeed: ['EPIC number or full name + constituency'], commonMistake: 'Going to the wrong booth. Always verify before polling day.', links: [{ text: 'ECI Electoral Search', url: 'https://electoralsearch.eci.gov.in/' }] },
  { id: 'checklist', title: 'Voting Day Checklist', description: 'Prepare everything you need for polling day', icon: 'list-checks', completed: false, active: false, checklist: ['Carry original Voter ID (EPIC) or approved photo ID', 'Find your name on the voter slip', 'Leave your mobile phone at home or outside the booth', 'Check your designated voting time slot to avoid queues'] },
  { id: 'mock-vote', title: 'How to Vote (Simulator)', description: 'Practice the full EVM + VVPAT voting process', icon: 'vote', completed: false, active: false, whatYouNeed: ['5 minutes of your time', 'Understanding of the EVM process'], commonMistake: 'Pressing the button multiple times — the EVM only accepts one press per ballot.' },
  { id: 'post-vote', title: 'Post-Vote: Verify & Follow Up', description: 'Check your vote was counted and results are declared', icon: 'flag', completed: false, active: false, whatYouNeed: ['Indelible ink mark on finger', 'Results tracking app/website'], commonMistake: 'Washing off ink immediately — it\'s a mark of civic pride that lasts 4-6 weeks!', links: [{ text: 'Official Election Results Portal', url: 'https://results.eci.gov.in/' }] },
];

export const existingVoterRoadmap: QuestStep[] = [
  { id: 'verify-reg', title: 'Verify Your Voter Details', description: 'Check your name, photo and address on the electoral roll', icon: 'search', completed: false, active: true, whatYouNeed: ['EPIC number or full name', 'Father/husband name'], commonMistake: 'Not checking before election — errors found on polling day cannot be fixed.', links: [{ text: 'Search in Electoral Roll', url: 'https://electoralsearch.eci.gov.in/' }] },
  { id: 'e-epic', title: 'Download e-EPIC', description: 'Get a digital copy of your Voter ID on your phone', icon: 'smartphone', completed: false, active: false, whatYouNeed: ['Registered mobile number', 'EPIC number'], commonMistake: 'Not having a backup ID if you lose the physical card.', links: [{ text: 'Download e-EPIC', url: 'https://voters.eci.gov.in/' }] },
  { id: 'candidate-kyc', title: 'Review Candidates', description: 'Compare candidates on education, wealth, and criminal record', icon: 'users', completed: false, active: false, whatYouNeed: ['Constituency name', 'Internet access'], commonMistake: 'Not checking criminal case details — "pending" doesn\'t mean innocent.', links: [{ text: 'Official ECI Candidate Affidavits', url: 'https://affidavit.eci.gov.in/' }] },
  { id: 'polling-lookup', title: 'Find Your Polling Booth', description: 'Locate your assigned polling station', icon: 'map-pin', completed: false, active: false, whatYouNeed: ['EPIC number'], commonMistake: 'Booths change between elections. Always re-verify!', links: [{ text: 'Know Your Polling Station', url: 'https://electoralsearch.eci.gov.in/' }] },
  { id: 'checklist', title: 'Voting Day Checklist', description: 'Ensure you have everything ready for election day', icon: 'list-checks', completed: false, active: false, checklist: ['Carry original Voter ID (EPIC) or approved photo ID', 'Confirm your polling booth location via the ECI site', 'Leave mobile phones and electronics outside the booth', 'Wear comfortable shoes for potential queues'] },
  { id: 'mock-vote', title: 'Cast Your Vote (Refresher)', description: 'Refresh your memory with the EVM simulator', icon: 'vote', completed: false, active: false, whatYouNeed: ['2 minutes of practice'], commonMistake: 'Pressing NOTA accidentally when you intended to vote for a candidate.' },
];

export const civicActionRoadmap: QuestStep[] = [
  { id: 'mcc', title: 'Understand Election Rules', description: 'The Model Code of Conduct (MCC) strictly prohibits hate speech, bribing voters, using government machinery for campaigns, and appealing to caste/communal feelings.', icon: 'book-open', completed: false, active: true, whatYouNeed: ['Access to ECI Model Code PDF'], commonMistake: 'Assuming MCC is legally binding — it\'s a convention, but ECI enforces it strictly.', links: [{ text: 'Read Official MCC Guidelines', url: 'https://www.eci.gov.in/mcc/' }] },
  { id: 'misinfo', title: 'Misinformation Detector Guide', description: 'Do not trust unverified social media forwards. Always check the source, look for official announcements, and use trusted fact-checking platforms.', icon: 'shield-check', completed: false, active: false, whatYouNeed: ['Critical thinking', 'Fact-checking websites'], commonMistake: 'Forwarding unverified WhatsApp messages without checking sources.', links: [{ text: 'AltNews Fact Check', url: 'https://www.altnews.in/' }, { text: 'Factly', url: 'https://factly.in/' }, { text: 'PIB Fact Check', url: 'https://factcheck.pib.gov.in/' }] },
  { id: 'report-violation', title: 'cVIGIL Complaint Flow', description: 'Report election violations to ECI using cVIGIL', icon: 'alert-triangle', completed: false, active: false, whatYouNeed: ['Smartphone with camera', 'GPS enabled', 'Description of violation'], commonMistake: 'Not including enough details or evidence in the report.', links: [{ text: 'Download Official cVIGIL App', url: 'https://cvigil.eci.gov.in/' }] },
  { id: 'track-issues', title: 'Track Reported Issues', description: 'Monitor the status of your filed complaints', icon: 'eye', completed: false, active: false, whatYouNeed: ['Complaint tracking ID'], commonMistake: 'Filing duplicate complaints instead of tracking existing ones.' },
  { id: 'candidate-kyc', title: 'Monitor Candidate Disclosures', description: 'Review financial affidavits and criminal declarations', icon: 'scale', completed: false, active: false, whatYouNeed: ['Access to ADR portal or ECI affidavit site'], commonMistake: 'Only looking at total assets without checking liabilities and cases.', links: [{ text: 'Official ECI Candidate Affidavits', url: 'https://affidavit.eci.gov.in/' }] },
];

export function getRoadmap(persona: string): QuestStep[] {
  switch (persona) {
    case 'new-voter': return newVoterRoadmap.map((s) => ({ ...s }));
    case 'existing-voter': return existingVoterRoadmap.map((s) => ({ ...s }));
    case 'civic-action': return civicActionRoadmap.map((s) => ({ ...s }));
    default: return [];
  }
}

