FROM node:20
WORKDIR /app

# Firebase config injected directly for reliable Cloud Build
ENV NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyBynWPFGuv-I_J2L_Bp8f2iKc74lj3CO7I
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=voter-pulse-ai-615e4.firebaseapp.com
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=voter-pulse-ai-615e4
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=voter-pulse-ai-615e4.firebasestorage.app
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1038499543051
ENV NEXT_PUBLIC_FIREBASE_APP_ID=1:1038499543051:web:4890a8eba6f688ff9a2f0e
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-P72ZY8Y4CF
ENV NEXT_PUBLIC_GA_ID=G-P72ZY8Y4CF
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

ENV PORT=8080
EXPOSE 8080

CMD ["npm", "start"]
